import { withExpand } from "../../resolvers";

const expand = {
  PaymentIntent: [
    "application",
    "customer",
    "customer.default_source",
    "on_behalf_of",
    "review",
    "review.charge",
    "review.charge.application",
    "review.charge.application_fee",
    "review.charge.application_fee.account",
    "review.charge.application_fee.application",
    "review.charge.balance_transaction",
    "review.charge.balance_transaction.source",
    "review.charge.customer",
    "review.charge.customer.default_source",
    "review.charge.dispute",
    "review.charge.dispute.charge",
    "review.charge.invoice",
    "review.charge.invoice.charge",
    "review.charge.invoice.customer",
    "review.charge.invoice.default_source",
    "review.charge.invoice.subscription",
    "review.charge.on_behalf_of",
    "review.charge.order",
    "review.charge.order.application",
    "review.charge.order.charge",
    "review.charge.order.customer",
    "review.charge.review",
    "review.charge.review.charge",
    "review.charge.review.payment_intent",
    "review.charge.source_transfer",
    "review.charge.source_transfer.balance_transaction",
    "review.charge.source_transfer.destination",
    "review.charge.source_transfer.destination_payment",
    "review.charge.source_transfer.source_transaction",
    "review.charge.transfer",
    "review.charge.transfer.balance_transaction",
    "review.charge.transfer.destination",
    "review.charge.transfer.destination_payment",
    "review.charge.transfer.source_transaction",
    "review.payment_intent",
    "review.payment_intent.application",
    "review.payment_intent.customer",
    "review.payment_intent.customer.default_source",
    "review.payment_intent.on_behalf_of",
    "review.payment_intent.review",
    "review.payment_intent.review.charge",
    "review.payment_intent.review.payment_intent",
    "review.payment_intent.source",
    "source"
  ],
  PaymentIntentList: [
    "data.application",
    "data.customer",
    "data.customer.default_source",
    "data.on_behalf_of",
    "data.review",
    "data.review.charge",
    "data.review.charge.application",
    "data.review.charge.application_fee",
    "data.review.charge.balance_transaction",
    "data.review.charge.customer",
    "data.review.charge.dispute",
    "data.review.charge.invoice",
    "data.review.charge.on_behalf_of",
    "data.review.charge.order",
    "data.review.charge.review",
    "data.review.charge.source_transfer",
    "data.review.charge.transfer",
    "data.review.payment_intent",
    "data.review.payment_intent.application",
    "data.review.payment_intent.customer",
    "data.review.payment_intent.on_behalf_of",
    "data.review.payment_intent.review",
    "data.review.payment_intent.source",
    "data.source"
  ]
};

export const expandResolvers = {
  "Query.retrievePaymentIntent": [withExpand(expand["PaymentIntent"])],
  "Query.listPaymentIntent": [withExpand(expand["PaymentIntentList"])],
  "Mutation.createPaymentIntent": [withExpand(expand["PaymentIntent"])],
  "Mutation.updatePaymentIntent": [withExpand(expand["PaymentIntent"])],
  "Mutation.confirmPaymentIntent": [withExpand(expand["PaymentIntent"])],
  "Mutation.capturePaymentIntent": [withExpand(expand["PaymentIntent"])],
  "Mutation.cancelPaymentIntent": [withExpand(expand["PaymentIntent"])]
};
